### ISSUE TITLE
websocket无法链接上去

### ISSUE THREAD

**Issue by hailunchina** [lzpong/TinyWeb#2]
websocket使用网页和QT以及纯C++都测试过，无法正常链接websocket，请检查。

**Comment by hailunchina** [comment]
websocket收发包有问题，收包的数据是乱码

**Comment by lzpong** [comment]
你抓包看看,发的数据是不是有问题

**Comment by hailunchina** [comment]
为自己倒一杯咖啡，为自己做一份早餐，请爱惜独一无二的自己吧，那是所有朋友对你的心愿。
